### ISSUE TITLE
Make text field to text area wherever needed

### ISSUE THREAD

**Issue by 1-Harshit** [spo-iitk/ras-frontend#11]

**Comment by 1-Harshit** [comment]
https://github.com/niuware/mui-rte
https://github.com/sstur/react-rte
https://github.com/quilljs/quill/blob/develop/docs/docs/modules/toolbar.md

or any other rte

**Comment by ManasGupta1310** [comment]
Zarurat ni hai....mui me multiline hota hai boht sexy lgta hai

**Comment by 1-Harshit** [comment]
rte chahiye inko,
docx se copy paste with same formatting
