### ISSUE TITLE
Stats page

### ISSUE THREAD

**Issue by 1-Harshit** [spo-iitk/ras-frontend#14]
- similar to #8 
- [Admin Side](https://www.figma.com/proto/Tn1nb3bB31R1h4irrGDX1q/SPO-Portal?node-id=25%3A4&scaling=min-zoom&page-id=0%3A1)
- page 49 `admin/rc/:id/stats/branch`
- page 50 `admin/rc/:id/stats/students`

**Comment by Krishnansh5** [comment]
claim

**Comment by ManasGupta1310** [comment]
Let me make the route to these pages and push them

**Comment by 1-Harshit** [comment]
- closed in #45
