### ISSUE TITLE
[ADMIN UI] Add Main RC and Notice tables

### ISSUE THREAD

**Issue by 1-Harshit** [spo-iitk/ras-frontend#16]
- [Admin](https://www.figma.com/proto/Tn1nb3bB31R1h4irrGDX1q/SPO-Portal?node-id=6%3A97&scaling=min-zoom&page-id=0%3A1) 
  -  Page 3 
    `/admin/rc/`
  - Page 7-8
    `/admin/rc/:id/notices`
![image](https://user-images.githubusercontent.com/75195728/171192523-1555dbbc-4f82-4353-b42a-18748d045797.png)

**Comment by amdpt323** [comment]
claim

**Comment by amdpt323** [comment]
- closes #16
