### ISSUE TITLE
[Admin UI] Create Recruitment Cycle homepage

### ISSUE THREAD

**Issue by 1-Harshit** [spo-iitk/ras-frontend#18]
[Admin page 6](https://www.figma.com/proto/Tn1nb3bB31R1h4irrGDX1q/SPO-Portal?node-id=7%3A2&scaling=min-zoom&page-id=0%3A1)
`/admin/rc/:id/`
![image](https://user-images.githubusercontent.com/75195728/171199058-b24be347-a92a-43a3-a7b7-9786facd88fb.png)

**Comment by utkarsh-tf141** [comment]
claim
