### ISSUE TITLE
[Admin UI] Add Notice, Company, PIO/PPO form

### ISSUE THREAD

**Issue by 1-Harshit** [spo-iitk/ras-frontend#19]
- [Admin Page 9](https://www.figma.com/proto/Tn1nb3bB31R1h4irrGDX1q/SPO-Portal?node-id=73%3A367&scaling=min-zoom&page-id=0%3A1)
  `/admin/rc/:id/notice/new`  
![image](https://user-images.githubusercontent.com/75195728/171200662-2e68cb66-d1cb-40f6-bab0-0ae5cb3de43f.png)

- Admin Page 11: `/admin/rc/:id/company/add`  
![image](https://user-images.githubusercontent.com/75195728/171200902-f9dce584-ae2f-4e25-b289-b684a12cd478.png)

- Admin Page 13: `/admin/rc/:id/pio-ppo/`
![image](https://user-images.githubusercontent.com/75195728/171200971-7c12c6e0-7316-4967-a843-a22374799c14.png)

**Comment by amdpt323** [comment]
claim
