### ISSUE TITLE
[Admin UI] Add company dashboard to RC

### ISSUE THREAD

**Issue by 1-Harshit** [spo-iitk/ras-frontend#20]
[Admin page 12](https://www.figma.com/proto/Tn1nb3bB31R1h4irrGDX1q/SPO-Portal?node-id=7%3A1122&scaling=min-zoom&page-id=0%3A1)
`/admin/rc/:id/company/:id`
![image](https://user-images.githubusercontent.com/75195728/171202683-64b85ab9-57bf-4499-a41c-b157015fa9ed.png)

**Comment by Krishnansh5** [comment]
claim
