### ISSUE TITLE
Add tooltips on long text in DataGrid

### ISSUE THREAD

**Issue by Krishnansh5** [spo-iitk/ras-frontend#211]

**Comment by 1-Harshit** [comment]
Tooltips?

**Comment by utkarsh-tf141** [comment]
Yes

**Comment by yashlm** [comment]
claim

**Comment by abhishekshree** [comment]
aye tooltip for long crappy HTML might suck
cc. @1-Harshit

**Comment by abhishekshree** [comment]
whats the use then

**Comment by 1-Harshit** [comment]
Which data grid we are talking about here?

**Comment by abhishekshree** [comment]
You tell

**Comment by utkarsh-tf141** [comment]
For any cell where the data overflows, such as name , company name,  email.
Tooltips can be useful .

**Comment by utkarsh-tf141** [comment]
Then, we can add it to relevant columns only ?

**Comment by 1-Harshit** [comment]
Yes
