### ISSUE TITLE
Add Student Image  

### ISSUE THREAD

**Issue by utkarsh-tf141** [spo-iitk/ras-frontend#214]
Image can be accessed from https://oa.cc.iitk.ac.in/Oa/Jsp/Photo/${roll_no}_0.jpg

**Comment by 1-Harshit** [comment]
Can also add student search dp :)
@abhishekshree ?

**Comment by abhishekshree** [comment]
I don't trust pclub with that

**Comment by 1-Harshit** [comment]
But it's just a url from cc homepage, right?

**Comment by abhishekshree** [comment]
yep, cc homepage is fine, but are you read for _all_ kinds of DP.jpg then?

**Comment by qu-bit1** [comment]
claim

**Comment by abhishekshree** [comment]
start working on it @qu-bit1 👍🏻

**Comment by utkarsh-tf141** [comment]
@qu-bit1 cache the image
