### ISSUE TITLE
[Admin UI] Add question ans

### ISSUE THREAD

**Issue by 1-Harshit** [spo-iitk/ras-frontend#24]
[Admin page 23](https://www.figma.com/proto/Tn1nb3bB31R1h4irrGDX1q/SPO-Portal?node-id=124%3A9176&scaling=min-zoom&page-id=0%3A1)
`/admin/rc/:id/jp/:id/question/new`
`/admin/rc/:id/jp/:id/question/:id`

- Can take help or blocked by/blocking #17

**Comment by utkarsh-tf141** [comment]
claim
