### ISSUE TITLE
[Admin UI] Add RC ALL company and student dashboard 

### ISSUE THREAD

**Issue by 1-Harshit** [spo-iitk/ras-frontend#26]
[Admin page 31-33](https://www.figma.com/proto/Tn1nb3bB31R1h4irrGDX1q/SPO-Portal?node-id=10%3A397&scaling=min-zoom&page-id=0%3A1)
`/admin/rc/:id/company/student`

[Admin page 10](https://www.figma.com/proto/Tn1nb3bB31R1h4irrGDX1q/SPO-Portal?node-id=7%3A872&scaling=min-zoom&page-id=0%3A1)
`/admin/rc/:id/company/all`

**Comment by abhishekshree** [comment]
You need to complete work on the previous issue @aastikg20

**Comment by shady141** [comment]
claim
