### ISSUE TITLE
[Admin UI] Add Forms

### ISSUE THREAD

**Issue by 1-Harshit** [spo-iitk/ras-frontend#27]
`/admin/rc/:id/student/enroll`
`/admin/rc/:id/student/freeze`
`/admin/rc/:id/student/unfreeze`
[Admin page 34-36](https://www.figma.com/proto/Tn1nb3bB31R1h4irrGDX1q/SPO-Portal?node-id=73%3A2841&scaling=min-zoom&page-id=0%3A1)

**Comment by amdpt323** [comment]
claim
