### ISSUE TITLE
[Admin UI] Resume Dashboard and attendence

### ISSUE THREAD

**Issue by 1-Harshit** [spo-iitk/ras-frontend#29]
[Admin page 38-39](https://www.figma.com/proto/Tn1nb3bB31R1h4irrGDX1q/SPO-Portal?node-id=11%3A710&scaling=min-zoom&page-id=0%3A1)
`/admin/rc/:id/resume/`

[Admin Page 42] 
`/admin/rc/:id/attendence/`

**Comment by Krishnansh5** [comment]
claim
