### ISSUE TITLE
[Admin UI] Add forms and stats

### ISSUE THREAD

**Issue by 1-Harshit** [spo-iitk/ras-frontend#32]
[Admin page 40-41] resume forms
`/admin/rc/:id/resume/bluk`
`/admin/rc/:id/resume/:id/clarification`
[admin page 49-50](https://www.figma.com/proto/Tn1nb3bB31R1h4irrGDX1q/SPO-Portal?node-id=26%3A211&scaling=min-zoom&page-id=0%3A1) Stats
`/admin/rc/:id/stats/students`
`/admin/rc/:id/stats/branch`

**Comment by shady141** [comment]
claim
