### ISSUE TITLE
[Admin UI] Master company database upsert/hr

### ISSUE THREAD

**Issue by 1-Harshit** [spo-iitk/ras-frontend#34]
[Admin page 55](https://www.figma.com/proto/Tn1nb3bB31R1h4irrGDX1q/SPO-Portal?node-id=75%3A4241&scaling=min-zoom&page-id=0%3A1)
`/admin/company/new`

[Admin page 58](https://www.figma.com/proto/Tn1nb3bB31R1h4irrGDX1q/SPO-Portal?node-id=75%3A4241&scaling=min-zoom&page-id=0%3A1)
`/admin/company/:id/edit`

[Admin page 59-60](https://www.figma.com/proto/Tn1nb3bB31R1h4irrGDX1q/SPO-Portal?node-id=75%3A4796&scaling=min-zoom&page-id=0%3A1)
`/admin/company/:id/hr/new`

[Admin page 62](https://www.figma.com/proto/Tn1nb3bB31R1h4irrGDX1q/SPO-Portal?node-id=75%3A5693&scaling=min-zoom&page-id=0%3A1)
`/admin/company/:id/comments`

**Comment by shady141** [comment]
claim
