### ISSUE TITLE
[Admin UI] Master database students 

### ISSUE THREAD

**Issue by 1-Harshit** [spo-iitk/ras-frontend#37]
[Admin page 64-65](https://www.figma.com/proto/Tn1nb3bB31R1h4irrGDX1q/SPO-Portal?node-id=32%3A132&scaling=min-zoom&page-id=0%3A1)
`/admin/student/`

[Admin page 66](https://www.figma.com/proto/Tn1nb3bB31R1h4irrGDX1q/SPO-Portal?node-id=32%3A132&scaling=min-zoom&page-id=0%3A1)
`/admin/student/freeze`

[Admin page 67](https://www.figma.com/proto/Tn1nb3bB31R1h4irrGDX1q/SPO-Portal?node-id=32%3A132&scaling=min-zoom&page-id=0%3A1)
`/admin/student/unfreeze`

**Comment by ahujatejas06** [comment]
claim
