### ISSUE TITLE
Add content to stats.tsx

### ISSUE THREAD

**Issue by ManasGupta1310** [spo-iitk/ras-frontend#8]
https://github.com/spo-iitk/ras-frontend/blob/main/pages/studentDashboard/internSeason/stats.tsx

Make the stats.tsx page resemble the following image as close as possible.
You are not expected to duplicate the content but add your ideas too to the page.
For the table component, you can take reference and code from [here.](https://github.com/spo-iitk/ras-frontend/tree/main/pages/companyDashboard/internSeason/applications)

### Content to be produced
![Screenshot from 2022-05-29 20-07-15](https://user-images.githubusercontent.com/84242412/170874941-f8e2b1d8-b4b5-4eac-86a1-0c0e9fee0223.png)

**Comment by utkarsh-tf141** [comment]
claim
