### ISSUE TITLE
Add events page

### ISSUE THREAD

**Issue by 1-Harshit** [spo-iitk/ras-frontend#9]
- [SPO secy Figma](https://www.figma.com/proto/Tn1nb3bB31R1h4irrGDX1q/SPO-Portal?node-id=100%3A47555&scaling=min-zoom&page-id=0%3A1) Page 27/28
   - /admin/jp/:id/events
   - /admin/jp/:id/events/:id/edit
 - [Company Figma](https://www.figma.com/proto/Tn1nb3bB31R1h4irrGDX1q/SPO-Portal?node-id=113%3A2807&scaling=min-zoom&page-id=80%3A6447) Page 7
   - /student/jp/:id/events

**Comment by aastikg20** [comment]
claim 
deadline- 3

**Comment by abhishekshree** [comment]
@ManasGupta1310 le rahe ye?
